// products
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING'
export const SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR'

// categories
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING'
export const SET_CATEGORY_ERROR = 'SET_CATEGORY_ERROR'
