// identity
export const SET_IDENTITY_LOADING = 'SET_IDENTITY_LOADING'
export const SET_IDENTITY_TOKEN = 'SET_IDENTITY_TOKEN'
export const SET_IDENTITY_ERROR = 'SET_IDENTITY_ERROR'
export const REMOVE_IDENTITY_TOKEN = 'REMOVE_IDENTITY_TOKEN'