// cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

// order
export const SET_ORDER_LOADING = 'SET_ORDER_LOADING'
export const SET_ORDER_ID = 'SET_ORDER_ID'
export const SET_ORDER_ERROR = 'SET_ORDER_ERROR'

// payment
export const SET_PAYMENT_LOADING = 'SET_PAYMENT_LOADING'
export const SET_PAYMENT_COMPLETED = 'SET_PAYMENT_COMPLETED'
export const SET_PAYMENT_ERROR = 'SET_PAYMENT_ERROR'
